from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from io import BytesIO
from django.http import HttpResponse

def generate_courses_pdf(eligible_programmes, user_points, user_grades):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=16,
        spaceAfter=30,
        textColor=colors.HexColor('#2c5aa0')
    )
    
    # Build the PDF content
    story = []
    
    # Title
    title = Paragraph("CoursePilot Kenya - Eligible Courses Report", title_style)
    story.append(title)
    story.append(Spacer(1, 0.2*inch))
    
    # User information
    user_info = Paragraph(f"<b>Your Cluster Points:</b> {user_points}", styles["Normal"])
    story.append(user_info)
    story.append(Spacer(1, 0.1*inch))
    
    # Eligible courses section
    courses_header = Paragraph("Eligible Degree Programs", styles["Heading2"])
    story.append(courses_header)
    story.append(Spacer(1, 0.1*inch))
    
    if not eligible_programmes:
        no_courses = Paragraph("No eligible courses found matching your criteria.", styles["Normal"])
        story.append(no_courses)
    else:
        # Create table data
        table_data = [['Programme', 'University', 'Required Points', 'Code']]
        
        for programme in eligible_programmes:
            table_data.append([
                programme['programme_name'],
                programme['university'],
                str(programme['required_cluster']),
                programme['programme_code']
            ])
        
        # Create table
        table = Table(table_data, colWidths=[2.5*inch, 2*inch, 1*inch, 1*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2c5aa0')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('FONTNAME', (0, 1), (-(-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
        ]))
        
        story.append(table)
    
    # Footer
    story.append(Spacer(1, 0.3*inch))
    footer = Paragraph(
        "Generated by CoursePilot Kenya - Always verify with official KUCCPS portal", 
        ParagraphStyle('Footer', parent=styles["Normal"], fontSize=8, textColor=colors.gray)
    )
    story.append(footer)
    
    # Build PDF
    doc.build(story)
    
    # Get PDF value
    pdf = buffer.getvalue()
    buffer.close()
    return pdf