# Generated by Django 5.2.8 on 2025-11-08 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_code', models.CharField(max_length=20, unique=True)),
                ('programme_name', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('cluster_points', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SubjectRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_1', models.CharField(max_length=100)),
                ('grade_1', models.CharField(max_length=5)),
                ('subject_2', models.CharField(blank=True, max_length=100, null=True)),
                ('grade_2', models.CharField(blank=True, max_length=5, null=True)),
                ('subject_3', models.CharField(blank=True, max_length=100, null=True)),
                ('grade_3', models.CharField(blank=True, max_length=5, null=True)),
                ('subject_4', models.CharField(blank=True, max_length=100, null=True)),
                ('grade_4', models.CharField(blank=True, max_length=5, null=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.programme')),
            ],
        ),
    ]
